"""
Constants file
"""
import os

VERSION = '2.4.1'
BOT_AUTHOR = 'kommotion'
POOPERSCOOPER_PICTURE = 'pooperscooper.jpg'
COOKS_AND_MOCHA = 'cooksandmocha.jpg'
COOKS = 'cooks.jpg'
GOOD_BOYS_AND_GIRLS = 'goodboysandgirls.jpg'
GAMETIME_JSON = 'gametime.json'
BIRTHDAY_JSON = 'birthday.json'
POLL_JSON = 'poll.json'
MENACES_TO_SOBRIETY_SERVER_ID = 932057681307512922
POOPER_SCOOPER_SUPPORT_SERVER_ID = 1045144253627637830
SECONDS_IN_HOUR = 3600
MINUTES_IN_HOUR = 60
THIRTY_SECONDS = 30
HOURS_IN_DAY = 24
EIGHT_HOURS_IN_SECONDS = 8 * SECONDS_IN_HOUR
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY
THUMBS_UP_EMOJI = '👍'

PALWORLD_JSON = 'palworld.json'
PALWORLD_UTIL_PATH = os.path.join(__file__, "utils", "palworld_utils")