"""
Constants file
"""
VERSION = '2.3.0'
BOT_AUTHOR = 'kommotion'
POOPERSCOOPER_PICTURE = 'pooperscooper.jpg'
COOKS_AND_MOCHA = 'cooksandmocha.jpg'
COOKS = 'cooks.jpg'
GOOD_BOYS_AND_GIRLS = 'goodboysandgirls.jpg'
GAMETIME_JSON = 'gametime.json'
BIRTHDAY_JSON = 'birthday.json'
POLL_JSON = 'poll.json'
MENACES_TO_SOBRIETY_SERVER_ID = 932057681307512922
POOPER_SCOOPER_SUPPORT_SERVER_ID = 1045144253627637830
SECONDS_IN_HOUR = 3600
MINUTES_IN_HOUR = 60
HOURS_IN_DAY = 24
SECONDS_IN_DAY = SECONDS_IN_HOUR * HOURS_IN_DAY
